---
# tasks file for php-fpm

- name: Install Ondrej PHP PPA
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: yes

- name: Install PHP-FPM Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_fpm_packages }}"
    - "{{ php_fpm_additional_packages }}"
  tags:
    - package
    - php-fpm

- name: Configure PHP-FPM
  when: php_fpm_config_files | length > 0
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ php_fpm_config_files }}"
  notify: "restart php-fpm"
  tags:
    - config
    - php-fpm

- name: Start end enable PHP-fpm
  service:
    name: "{{ php_fpm_service_name }}"
    enabled: yes
    state: started
  tags:
    - service
    - php-fpm
